### ISSUE TITLE
Crashlyticsの導入

### ISSUE THREAD

**Issue by yoshiyasuko** [yoshiyasuko/MyTaskManagement#51]
## Overview
- クラッシュログ追跡のためにCrashlyticsを導入する

## Task list
- [x] Release と Debug でアプリIDを分ける
- [x] Debug用のアプリをFirebaseに追加し、 `google-services.json` を取得
- [x] app/build.gradle.kts に Debug ビルドのアプリIDには `.debug` をSuffixで付与する
- [x] Debug でクラッシュさせて、Debug 用のアプリにログが飛ぶか確認する
